### ISSUE TITLE
Unable to Send or Claim Transaction - Insufficient Funds for Gas Error

### ISSUE THREAD

**Issue by Crack000-Com** [Soneium/soneium-node#10]
Hi,
I’m having trouble sending or claiming my transaction. I used to be able to do this, but now I keep getting an error message that says “insufficient funds for gas * price + value” even though I’ve added more funds to my wallet. I’ve tried increasing the balance, but it still doesn’t work. Could you help me understand why this is happening and what I can do to fix it?
![Screenshot_20241015-062313_Pixel Launcher](https://github.com/user-attachments/assets/5d1b802f-1910-4f52-8c85-1137108ccf20)

**Comment by Gunit2481** [comment]
Hello,

The issue occurs because your wallet on Sepolia network doesn't have enough funds (sETH) to cover the gas fees needed to prove or claim tokens from the bridge.

To solve this problem, make sure you top up your wallet with sETH on Sepolia.

Gas fees to prove or claim transactions vary according to activity and congestion on Sepolia network. Higher activity increases Gwei and gas fees. You can follow Sepolia's activity here : https://sepolia.beaconcha.in/gasnow

If you need further assistance, please join[ Soneium's Discord](https://discord.com/invite/soneium) and open a ticket. Our support team will be happy to help you.

Sony Block Solutions Labs

**Comment by bLd75** [comment]
I am closing this issue, outside of the repo scope.

**Comment by Crack000-Com** [comment]
But the balance is enough to cover the gas fee, as shown in the screenshot. The gas fee is only 0.004739 SepoliaETH, and I have 0.78323 SepoliaETH available. Could you please check what's going wrong?
![IMG_20241016_053730](https://github.com/user-attachments/assets/8d0ff3ac-6082-4a89-867b-f5c0e8aab7c7)
